### ISSUE TITLE
Problem in rendering trelliscope graph in .md github file

### ISSUE THREAD

**Issue by vivvi87** [hafen/trelliscopejs#106]
Hello, 
I made a R markdown file containing a trelliscope graph and I would like to get an md file that can be seen in github.
In order to render trelliscope on the Rmd I need the following yalm:

```
    title: "Worldwide Covid-19 incidence over time"
    date: "`r format(Sys.time(), '%d %B %Y')`"
    output:
       html_document:
          keep_md: true
          self_contained: false
          lib_dir: rmarkdown_files
```

Though this does not render well as md file in github. I tried to add:

```
    title: "Worldwide Covid-19 incidence over time"
    date: "`r format(Sys.time(), '%d %B %Y')`"
    output:
       github_document:
       html_document:
          keep_md: true
          self_contained: false
          lib_dir: rmarkdown_files
```

But I get an error message:

```
PhantomJS not found. You can install it with webshot::install_phantomjs(). If it is installed, please make sure the phantomjs executable can be found via the PATH variable.
output file: Covid_timeline_wrld.knit.md

Error: Functions that produce HTML output found in document targeting gfm output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: true

Note however that the HTML output will not be visible in non-HTML formats.

In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

Does anyone know how I can solve the issue?
Thanks
