### ISSUE TITLE
Rmarkdown error

### ISSUE THREAD

**Issue by EnricowithR** [hafen/trelliscopejs#13]
The package it works when I run it alone but when I run it in Rmarkdown I get the following error:
Error in if (!grepl("^[A-Za-z0-9_]", orig_path)) stop_nice("Path for trelliscope output while inside knitr must be relative.") : 
  argument is of length zero
Calls: <Anonymous> ... knit_print.facet_trelliscope -> print.facet_trelliscope -> resolve_app_params

This is the code that I am using, including the self_cointained option:
facet_trelliscope(~ myvariable,  nrow = 2, ncol = 2, self_contained = TRUE)

What should I do in order to use the package with Rmarkdown?

**Comment by mwhitaker** [comment]
You'll want to have this in your `yaml` block in the Rmarkdown file:

```
---
title: "Trelliscope"
author: "Michael Whitaker"
date: "December 3, 2016"
output:
   html_document:
      self_contained: false
      lib_dir: rmarkdown_files
---
```

And in your chunk add the **path** parameter:

```{r trelliscope, echo=FALSE, message=FALSE}
library(trelliscopejs)
library(dplyr)
library(ggplot2)
library(rbokeh)

d <- mpg %>%
  group_by(manufacturer, class) %>%
  summarise(
    panel = panel(
      figure(xlab = "City mpg", ylab = "Highway mpg") %>%
        ly_points(cty, hwy)))

d %>% trelliscope(name = "city_vs_highway_mpg", path = "rmarkdown_files")
```

Then press **Knit** and voilà, all your dependencies are in the **rmarkdown_files** folder and you get a nice html output file.
